# Generated by Django 4.2.7 on 2023-11-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoppingtrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_ID', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Gender', models.TextField()),
                ('Item_Purchased', models.TextField()),
                ('Category', models.TextField()),
                ('Purchase_Amount_USD', models.IntegerField()),
                ('Location', models.TextField()),
                ('Size', models.TextField()),
                ('Color', models.TextField()),
                ('Season', models.TextField()),
                ('Review_Rating', models.IntegerField()),
                ('Subscription_Status', models.TextField()),
                ('Shipping_Type', models.TextField()),
                ('Discount_Applied', models.TextField()),
                ('Promo_Code_Used', models.TextField()),
                ('Previous_Purchases', models.IntegerField()),
                ('Payment_Method', models.TextField()),
                ('Frequency_of_Purchases', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
