# Generated by Django 4.2.7 on 2023-11-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shoppingtrends_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingtrends',
            name='Preferred_Payment_Method',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
