# Generated by Django 4.2.7 on 2023-11-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shoppingtrends_preferred_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingtrends',
            name='Preferred_Payment_Method',
        ),
    ]
